version: '3.8'

services:
  app:
    build: .
    networks:
      - workspace
    volumes:
      - ..:/usr/src

  mysql:
    image: mysql:latest
    networks:
      - workspace
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db

networks:
  workspace:
