version: '3.8'

services:
  app:
    image: python:3.11-bullseye
    networks:
      - workspace
    volumes:
      - ..:/usr/src
    environment:
      - ZDOTDIR=/usr/src/.dotfiles/zsh

  mysql:
    image: mysql:latest
    networks:
      - workspace
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_db

networks:
  workspace:
