name: Django Deploy Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Django Deploy Check
      run: |
        python -m django check --deploy
        if [[ $? -ne 0 ]]; then
          echo "Django check --deploy failed with warnings"
          exit 1
        fi